# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: Tag web version and create draft release

on:
  workflow_dispatch:
    inputs:
      commit:
        description: commit sha of version
        required: true
      version:
        description: new version number (x.y.z)
        required: true
      product:
        type: choice
        options:
          - web
          - unified
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_sha: ${{ github.event.inputs.commit }}
          custom_tag: ${{ github.event.inputs.version }}
          tag_prefix: '${{ github.events.inputs.product }}@'

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Accessibility Insights for ${{ github.event.inputs.product }} v${{ github.event.inputs.version }}
          body: ${{ steps.tag_version.outputs.changelog }}
